package tool.clients.fmmlxdiagrams;

public enum DiagramToolBarProperties {
	SHOWOPERATIONS,
	SHOWOPERATIONVALUES,
	SHOWSLOTS,
	SHOWGETTERSANDSETTERS,
	SHOWDERIVEDOPERATIONS,
	SHOWDERIVEDATTRIBUTES,
	SHOWCONSTRAINTS,
	SHOWCONSTRAINTREPORTS,
	SHOWMETACLASSNAME,
	SHOWCONCRETESYNTAX,
	SHOWISSUETABLEVISIBLE
}
