package tool.clients.fmmlxdiagrams;

public enum DiagramToolBarProperties {
	OPERATIONS,
	OPERATIONVALUES,
	SLOTS,
	GETTERSANDSETTERS,
	DERIVEDOPERATIONS,
	DERIVEDATTRIBUTES,
	CONSTRAINTS,
	CONSTRAINTREPORTS,
	METACLASSNAME,
	CONCRETESYNTAX,
	ISSUETABLEVISIBLE
}
